### PR TITLE
Update README.md to add logo

### PR DESCRIPTION
**Pull request by quantumjot**

### CODE REVIEW

**Review by IFenton — APPROVED** [review]
LGTM

**Review by evangeline-corcoran — APPROVED** [review]
I like it!

**Review by acocac — APPROVED** [review]
LGTM 🪨

**Comment by quantumjot** [comment]
Let's do this!

**Comment by aldenc** [comment]
I like it! and I know it's already been merged but if I had to change one thing I would make the pixel at the end of the P the same width as the P so it's not sticking out

**Pull request merged**
